# HTCondor Submission File for Grid ISIC Bulk Certification (resnet18)
# Runs in docker container with parallel GPU support

universe                = docker
docker_image            = nvidia/cuda:12.1.0-runtime-ubuntu22.04
initialdir              = /home/exml_team007/certified-attribution-medical-imaging
executable              = bulk_certify_grid_isic.sh
transfer_input_files    = bulk_certify_grid_isic.sh, certify_grid_isic_server.py, run_bulk_certify_grid_isic.py

arguments               = --grid_pt /home/exml_team007/certified-attribution-medical-imaging/data/raw/grid/isic/val/grid.pt --checkpoint /home/exml_team007/certified-attribution-medical-imaging/outputs/checkpoints/isic/resnet18/final_model.pt --output_base /home/exml_team007/certified-attribution-medical-imaging/outputs/bulk_certifcation/grid_2/isic/resnet18 --num_samples 100 --batch_size 16 --sigma 0.15 --tau 0.75 --alpha 0.001 --k_percents 50 25 5

environment             = "PROJECT_ROOT=/home/exml_team007/certified-attribution-medical-imaging CONDA_PYTHON_BINARY_PATH=/home/exml_team007/miniconda3/envs/certified-attribution-medical-imaging/bin/python"

output                  = /home/exml_team007/condor_logs/bulk_certify_grid_isic.$(ClusterId).$(ProcId).out
error                   = /home/exml_team007/condor_logs/bulk_certify_grid_isic.$(ClusterId).$(ProcId).err
log                     = /home/exml_team007/condor_logs/bulk_certify_grid_isic.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_GPUs  = 1
request_CPUs  = 4
request_memory = 16G
request_disk   = 15G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1
