#!/usr/bin/env python
"""Grid ISIC Certification Server - multi-head per-cell attribution certification."""

import sys
from pathlib import Path
import argparse
import pickle
from datetime import datetime

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from tqdm import tqdm
import numpy as np

ROOT = Path.cwd().resolve()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.datasets.grid_dataset import GridDataset
from src.models.grid_multihead import GridMultiHead
from src.certify.smoothing import RandomizedSmoothingAttributor
from src.xai.attribution_unified import (
    IntegratedGradientsUnified,
    GradCAMUnified,
    RISEUnified,
    OcclusionUnified,
    LRPUnified,
)


def get_resnet_target_layer(model: GridMultiHead):
    # For ResNet backbones: last conv in layer4
    try:
        layer4 = model.feature_extractor.body[6]  # layer4 module
        return layer4[-1].conv2 if hasattr(layer4[-1], "conv2") else layer4[-1]
    except Exception:
        # Fallback: last Conv2d
        for _, module in reversed(list(model.named_modules())):
            if isinstance(module, nn.Conv2d):
                return module
    raise ValueError("Could not find target layer for GradCAM")


class HeadWrapper(nn.Module):
    def __init__(self, grid_model: GridMultiHead, head_id: int):
        super().__init__()
        self.grid_model = grid_model
        self.head_id = head_id

    def forward(self, x: torch.Tensor):
        return self.grid_model(x, head_id=self.head_id)


def build_attr_methods(grid_model: GridMultiHead, device: str, head_id: int):
    wrapper = HeadWrapper(grid_model, head_id)
    target_layer = get_resnet_target_layer(grid_model)
    return {
        "GradCAM": GradCAMUnified(wrapper, target_layer, device),
        "IntegratedGradients": IntegratedGradientsUnified(wrapper, device),
        "RISE": RISEUnified(wrapper, device),
        "Occlusion": OcclusionUnified(wrapper, device),
        "LRP": LRPUnified(wrapper, device, epsilon=1e-6),
    }


def parse_args():
    p = argparse.ArgumentParser("Grid ISIC Certification")
    p.add_argument("--grid_pt", required=True, help="Path to grid.pt generated by generate_grid_dataset")
    p.add_argument("--checkpoint", required=False, default=None, help="Optional single-head checkpoint to init backbone weights")
    p.add_argument("--num_classes", type=int, default=8)
    p.add_argument("--device", default=("cuda" if torch.cuda.is_available() else "cpu"))
    p.add_argument("--sigma", type=float, default=0.15)
    p.add_argument("--num_samples", type=int, default=100)
    p.add_argument("--tau", type=float, default=0.75)
    p.add_argument("--alpha", type=float, default=0.001)
    p.add_argument("--batch_size", type=int, default=1)
    p.add_argument("--k_percents", type=int, nargs="+", default=[50, 25, 5])
    p.add_argument("--save_dir", default=str(ROOT / "outputs" / "certifications" / "grid_isic"))
    p.add_argument("--save_noisy_samples", action="store_true")
    p.add_argument("--max_noisy_samples", type=int, default=3)
    return p.parse_args()


def load_model(num_heads: int, num_classes: int, device: str, checkpoint: str = None) -> GridMultiHead:
    model = GridMultiHead("resnet18", num_classes=num_classes, num_heads=num_heads, pretrained=(checkpoint is None))
    if checkpoint:
        state = torch.load(checkpoint, map_location=device)
        if isinstance(state, dict) and "state_dict" in state:
            state = state["state_dict"]
        model_dict = model.state_dict()
        state = {k.replace("module.", ""): v for k, v in state.items() if k.replace("module.", "") in model_dict}
        model_dict.update(state)
        model.load_state_dict(model_dict, strict=False)
        model.duplicate_head_weights(0)
    model.to(device)
    model.eval()
    return model


def main():
    args = parse_args()
    device = args.device

    # Load grid dataset
    grid_ds = GridDataset(Path(args.grid_pt))
    num_heads = grid_ds.scale * grid_ds.scale
    loader = DataLoader(grid_ds, batch_size=1, shuffle=False)

    # Model
    model = load_model(num_heads=num_heads, num_classes=args.num_classes, device=device, checkpoint=args.checkpoint)

    results = {}
    for batch_idx, sample in enumerate(tqdm(loader, desc="Certifying grids")):
        image = sample["image"].to(device)
        target_class = int(sample["target_class"].item())
        head_id = int(sample["target_head"].item())
        scale = int(sample["meta"]["scale"].item()) if isinstance(sample["meta"], dict) and "scale" in sample["meta"] else grid_ds.scale

        methods = build_attr_methods(model, device, head_id)
        smoother = RandomizedSmoothingAttributor(model, None, device=device)

        # Build attribution wrappers that ignore target_class override
        def make_attr_wrapper(attr_obj):
            def _fn(img, target_class_override=None):
                tc = target_class if target_class_override is None else int(target_class_override)
                return attr_obj.attribute(img, target_class=tc)
            return _fn

        for mname, attr_obj in methods.items():
            for k in args.k_percents:
                smoother.attribution_func = make_attr_wrapper(attr_obj)
                res = smoother.certify(
                    image,
                    k_percent=k,
                    target_class=target_class,
                    sigma=args.sigma,
                    num_samples=args.num_samples,
                    tau=args.tau,
                    batch_size=args.batch_size,
                    alpha=args.alpha,
                    save_noisy_samples=args.save_noisy_samples,
                    max_noisy_samples=args.max_noisy_samples,
                )
                results.setdefault(mname, {}).setdefault(k, []).append({
                    "image_idx": batch_idx,
                    "label": target_class,
                    "head_id": head_id,
                    "scale": scale,
                    "target_cell": grid_ds.target_cell,
                    "results": res,
                })

    save_dir = Path(args.save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    pkl_path = save_dir / f"results_{ts}.pkl"
    with open(pkl_path, "wb") as f:
        pickle.dump({"resnet18": results}, f)
    print(f"Saved certification results to {pkl_path}")


if __name__ == "__main__":
    main()
