universe                = docker
docker_image            = nvidia/cuda:12.1.0-runtime-ubuntu22.04
initialdir              = /home/exml_team007/certified-attribution-medical-imaging
executable              = execute_attribution_fundus.sh
transfer_input_files    = execute_attribution_fundus.sh
arguments               = --num_samples 10 --batch_size 4 --num_workers 4

output                  = /home/exml_team007/condor_logs/attribution_fundus.$(ClusterId).$(ProcId).out
error                   = /home/exml_team007/condor_logs/attribution_fundus.$(ClusterId).$(ProcId).err
log                     = /home/exml_team007/condor_logs/attribution_fundus.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_GPUs  = 1
request_CPUs  = 4
request_memory = 16G
request_disk   = 20G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1
