#!/usr/bin/env bash
# Quick start guide for running certified attribution on grid dataset

echo "======================================================================"
echo "DiFull Certified Attribution - Quick Start Guide"
echo "======================================================================"
echo ""
echo "The sparsification fix has been applied and verified."
echo "You can now run full certification on the grid dataset."
echo ""
echo "Prerequisites:"
echo "  1. Grid dataset: data/processed/isic/grid_2x2.pt"
echo "  2. Model checkpoint (optional, uses pretrained ResNet18 if not provided)"
echo ""
echo "======================================================================"
echo "COMMAND 1: Certification with default parameters"
echo "======================================================================"
echo ""
echo "python certify_grid_isic_server.py \\"
echo "    --grid_pt data/processed/isic/grid_2x2.pt \\"
echo "    --num_classes 8 \\"
echo "    --device cuda \\"
echo "    --sigma 0.15 \\"
echo "    --num_samples 100 \\"
echo "    --tau 0.75 \\"
echo "    --k_percents 50 25 5 \\"
echo "    --save_dir outputs/certifications/grid_isic \\"
echo "    --heatmap_dir outputs/bulk_certifcation/grid/isic/resnet18/certified_maps"
echo ""
echo "======================================================================"
echo "COMMAND 2: Quick test with fewer samples (faster)"
echo "======================================================================"
echo ""
echo "python certify_grid_isic_server.py \\"
echo "    --grid_pt data/processed/isic/grid_2x2.pt \\"
echo "    --num_samples 20 \\"
echo "    --k_percents 50"
echo ""
echo "======================================================================"
echo "PARAMETER GUIDE"
echo "======================================================================"
echo ""
echo "  --grid_pt:        Path to grid dataset (grid_2x2.pt)"
echo "  --num_classes:    Number of classes (default: 8)"
echo "  --checkpoint:     Optional pre-trained checkpoint"
echo "  --device:         'cuda' or 'cpu' (auto-detect if not specified)"
echo "  --sigma:          Noise std deviation (paper: 0.15, higher = more noise)"
echo "  --num_samples:    Num noisy samples (paper: 100, more = better but slower)"
echo "  --tau:            Certification threshold (paper: 0.75, higher = stricter)"
echo "  --k_percents:     Sparsification levels to test (paper: [50, 25, 5])"
echo "  --alpha:          Confidence level (paper: 0.001, smaller = tighter bounds)"
echo "  --save_dir:       Output directory for pickle results"
echo "  --heatmap_dir:    Output directory for certified maps and visualizations"
echo ""
echo "======================================================================"
echo "EXPECTED OUTPUT"
echo "======================================================================"
echo ""
echo "After running certification, you should see:"
echo ""
echo "1. Console output:"
echo "   [Randomized Smoothing] σ=0.15, τ=0.75, n=100, K=50%"
echo "   Smoothing samples: 100%"
echo "   [Results] Certified: XX.X% | Abstained: XX.X% | Radius: X.XXXX"
echo ""
echo "2. Output files:"
echo "   - outputs/certifications/grid_isic/results_YYYYMMDD_HHMMSS.pkl"
echo "   - outputs/bulk_certifcation/grid/isic/resnet18/certified_maps/"
echo "     - arrays/resnet18/[METHOD]/k_[K]/"
echo "     - viz/resnet18/[METHOD]/k_[K]/"
echo "     - panels/"
echo ""
echo "3. Visualization:"
echo "   - PNG overlays showing certified attributions"
echo "   - Paper-style panels with all methods and K values"
echo ""
echo "======================================================================"
echo "WHAT THE FIX DOES"
echo "======================================================================"
echo ""
echo "The sparsification fix changes how sparse attributions are handled:"
echo ""
echo "OLD (broken):  Uses percentile threshold"
echo "               → All pixels marked as '1' when sparse"
echo "               → Uniform certified maps (all orange or all white)"
echo ""
echo "NEW (fixed):   Uses ranking-based top-K selection"
echo "               → Target cell pixels rank highest"
echo "               → Non-target cells properly separated"
echo "               → Certified maps localize to target cell ✓"
echo ""
echo "======================================================================"
echo "VERIFICATION"
echo "======================================================================"
echo ""
echo "To verify the fix is working:"
echo ""
echo "python sanity_check_sparsification_fix.py"
echo ""
echo "Expected output:"
echo "  Cell 0 (target): 100.0% certified as '1'"
echo "  Cell 1 (other):  100.0% abstained (properly distinguished)"
echo "  ✅ SPARSIFICATION FIX VERIFIED"
echo ""
echo "======================================================================"
echo ""
