universe                = docker
docker_image            = nvidia/cuda:12.1.0-runtime-ubuntu22.04
initialdir              = /home/exml_team007/certified-attribution-medical-imaging
executable              = execute_train_chestxray.sh
transfer_input_files    = execute_train_chestxray.sh
arguments               = --epochs 50 --batch_size 32 --num_workers 4 --metric val_accuracy --resume
environment             = "PROJECT_ROOT=/home/exml_team007/certified-attribution-medical-imaging CONDA_PYTHON_BINARY_PATH=/home/exml_team007/miniconda3/envs/certified-attribution-medical-imaging/bin/python PYTHON_SCRIPT=train_chestxray_server.py"

output                  = /home/exml_team007/condor_logs/train_chestxray.$(ClusterId).$(ProcId).out
error                   = /home/exml_team007/condor_logs/train_chestxray.$(ClusterId).$(ProcId).err
log                     = /home/exml_team007/condor_logs/train_chestxray.$(ClusterId).log

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

request_GPUs  = 1
request_CPUs  = 4
request_memory = 16G
request_disk   = 10G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1
